{
  "formatVersion": "1.1",
  "component": {
    "url": "../../abstract-red-black-priority-queue/1.1/abstract-red-black-priority-queue-1.1.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "abstract-red-black-priority-queue",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-tree",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-priority-queue-js-1.1.klib",
          "url": "abstract-red-black-priority-queue-js-1.1.klib",
          "size": 12730,
          "sha512": "5a91f58e08209e43049045808a850796018b144ce5b5d75ae08a92bfd9786fb30749a6a869c278cf8dc791a5b602189c1188cd6c6f785ead93fd289df8b61520",
          "sha256": "d8321521130153814627d88a4979dda85cd2855491b94560041e0eb542c2f40d",
          "sha1": "2422f841dd93323a51b5c76d4fdbfaaf6a025996",
          "md5": "92521e2aa289b06fcd675cbe439e1616"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-tree",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-priority-queue-js-1.1.klib",
          "url": "abstract-red-black-priority-queue-js-1.1.klib",
          "size": 12730,
          "sha512": "5a91f58e08209e43049045808a850796018b144ce5b5d75ae08a92bfd9786fb30749a6a869c278cf8dc791a5b602189c1188cd6c6f785ead93fd289df8b61520",
          "sha256": "d8321521130153814627d88a4979dda85cd2855491b94560041e0eb542c2f40d",
          "sha1": "2422f841dd93323a51b5c76d4fdbfaaf6a025996",
          "md5": "92521e2aa289b06fcd675cbe439e1616"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "abstract-red-black-priority-queue-js-1.1-sources.jar",
          "url": "abstract-red-black-priority-queue-js-1.1-sources.jar",
          "size": 2684,
          "sha512": "9295885cf78a625a118399347e8c739de0f5deaea4d82acea690cdb1752a6a70bc344f72f0f098f68831bc09c8941f428390621abfb6a9d108048eb95f74452b",
          "sha256": "31440029b58b89417ec68ea8046cc01e65c2b17e29ed7a645a62f0c57531ee91",
          "sha1": "751f0b2471becf15e9b13040b4a9e491128e8aaa",
          "md5": "4b55e277a7751ec73c43f5575edf8c14"
        }
      ]
    }
  ]
}
