{
  "formatVersion": "1.1",
  "component": {
    "url": "../../abstract-red-black-priority-queue/1.1/abstract-red-black-priority-queue-1.1.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "abstract-red-black-priority-queue",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-tree",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-priority-queue.klib",
          "url": "abstract-red-black-priority-queue-androidnativex64-1.1.klib",
          "size": 14989,
          "sha512": "ee89b443c8052542a3966bfa8361a15e6b3f03674e271884a117bf5d753b4b30e70622ac21f6a066729a4379b89fb85ad8cca84607083822d6cc31c07f0e4dc1",
          "sha256": "e54597faa0c1a7c3256031275ee4c0fc8a5e3ee29fe65704b4619e22c0d9c6cc",
          "sha1": "43e45086f0f798aa5ceafe8d3b647e17318f4ccb",
          "md5": "0c3839d0a1d18f9997ed1b0832bbacc2"
        }
      ]
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "abstract-red-black-priority-queue-androidnativex64-1.1-sources.jar",
          "url": "abstract-red-black-priority-queue-androidnativex64-1.1-sources.jar",
          "size": 2684,
          "sha512": "9295885cf78a625a118399347e8c739de0f5deaea4d82acea690cdb1752a6a70bc344f72f0f098f68831bc09c8941f428390621abfb6a9d108048eb95f74452b",
          "sha256": "31440029b58b89417ec68ea8046cc01e65c2b17e29ed7a645a62f0c57531ee91",
          "sha1": "751f0b2471becf15e9b13040b4a9e491128e8aaa",
          "md5": "4b55e277a7751ec73c43f5575edf8c14"
        }
      ]
    }
  ]
}
