{
  "formatVersion": "1.1",
  "component": {
    "url": "../../abstract-red-black-priority-queue/1.0/abstract-red-black-priority-queue-1.0.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "abstract-red-black-priority-queue",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-tree",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-priority-queue.klib",
          "url": "abstract-red-black-priority-queue-linuxarm64-1.0.klib",
          "size": 13448,
          "sha512": "a29b222063fd48adcb7833affd8c39e473159e3db3b6a40f7aabe6aa89ef64f17764014dde0a20d22ad3fa8c2919fcd09ff27e16f4fed4856a9ec42be7363973",
          "sha256": "a84e18eabffea975ad0c862fe0124e94abc9fcac32dbe90c100da949bd5e5a44",
          "sha1": "bf7cf4d2fc827cd012bb0b62bcfea9a219914503",
          "md5": "c65368388f3ce48d892c0a2ff3e52ad3"
        }
      ]
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "abstract-red-black-priority-queue-linuxarm64-1.0-sources.jar",
          "url": "abstract-red-black-priority-queue-linuxarm64-1.0-sources.jar",
          "size": 2386,
          "sha512": "bf8eacd8269746ec6ae1a687f4921866ab7e60738d93bbd42343b091b02cea8b876cfc0def39265fa51964a892fd1d47ae11d07a9d10116c60baeb667fd948f4",
          "sha256": "f08bfd49ad8448dcd8b4e4d4eb30507be68b85370301794c305e1953f6b3755e",
          "sha1": "baed2e53dc52e001f9d48c5ee65759cbb09f5624",
          "md5": "e6cec4710f91cdc20677c3cda9c1d5b3"
        }
      ]
    }
  ]
}
