{
  "formatVersion": "1.1",
  "component": {
    "url": "../../abstract-red-black-priority-queue/1.1/abstract-red-black-priority-queue-1.1.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "abstract-red-black-priority-queue",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-tree",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-priority-queue.klib",
          "url": "abstract-red-black-priority-queue-macosarm64-1.1.klib",
          "size": 14988,
          "sha512": "c358575379d167625a3a78eefeee383a1718fe806571d8a7c77763f7a2d63473f53e0b75c1a230602f4640e69898f0944a3ddaa133973cc326aecb438a8e1957",
          "sha256": "d6a68fde118edd72d5b9850bc3ee2b90b6d04b8279badae25d4a27b31f29e497",
          "sha1": "7c96c14ee82cf52af7726ea22d5c97c1322939fc",
          "md5": "254bfeb88c7035177b805934fe2cec7d"
        }
      ]
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "abstract-red-black-priority-queue-macosarm64-1.1-sources.jar",
          "url": "abstract-red-black-priority-queue-macosarm64-1.1-sources.jar",
          "size": 2684,
          "sha512": "9295885cf78a625a118399347e8c739de0f5deaea4d82acea690cdb1752a6a70bc344f72f0f098f68831bc09c8941f428390621abfb6a9d108048eb95f74452b",
          "sha256": "31440029b58b89417ec68ea8046cc01e65c2b17e29ed7a645a62f0c57531ee91",
          "sha1": "751f0b2471becf15e9b13040b4a9e491128e8aaa",
          "md5": "4b55e277a7751ec73c43f5575edf8c14"
        }
      ]
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-tree",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-priority-queue-macosarm64-1.1-metadata.jar",
          "url": "abstract-red-black-priority-queue-macosarm64-1.1-metadata.jar",
          "size": 261,
          "sha512": "c1c9e6a8e4e7ff4aef70946619f0209282d67689538168e256354fe8d52d606ec1ffd4ff822c9573fac324cd6605944585f12c399dbd84867e8c3d1d651c42fb",
          "sha256": "c62349db066a1a45196c56d1e7ba00c6d92266fbc83dd428fa2c3b42486b0b08",
          "sha1": "8e7508659124f6293893d9be404a089fe2029014",
          "md5": "e02deba005a0eaef18c5d2f6456e4cbd"
        }
      ]
    }
  ]
}
