{
  "formatVersion": "1.1",
  "component": {
    "url": "../../abstract-red-black-priority-queue/1.1/abstract-red-black-priority-queue-1.1.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "abstract-red-black-priority-queue",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-tree",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-priority-queue.klib",
          "url": "abstract-red-black-priority-queue-tvosx64-1.1.klib",
          "size": 14964,
          "sha512": "d5c23684b1a02782638d9ee02f766112a91cdf4f8c4e4981b7a5bc0cb309331fc0e330f7b081563689993617fb00037efc6b1914a64a3e92674782aae055af92",
          "sha256": "879f858b494a873fda5183329d17cf0903c8863d64d436cc0b3a528868011ed8",
          "sha1": "851a97e2d08185c4818315bbd57354411a7fb4f5",
          "md5": "b639da76e5a05b2aef64c9c17bb9b803"
        }
      ]
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "abstract-red-black-priority-queue-tvosx64-1.1-sources.jar",
          "url": "abstract-red-black-priority-queue-tvosx64-1.1-sources.jar",
          "size": 2684,
          "sha512": "9295885cf78a625a118399347e8c739de0f5deaea4d82acea690cdb1752a6a70bc344f72f0f098f68831bc09c8941f428390621abfb6a9d108048eb95f74452b",
          "sha256": "31440029b58b89417ec68ea8046cc01e65c2b17e29ed7a645a62f0c57531ee91",
          "sha1": "751f0b2471becf15e9b13040b4a9e491128e8aaa",
          "md5": "4b55e277a7751ec73c43f5575edf8c14"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-tree",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-priority-queue-tvosx64-1.1-metadata.jar",
          "url": "abstract-red-black-priority-queue-tvosx64-1.1-metadata.jar",
          "size": 261,
          "sha512": "f011a5466eb3bd984f3fbb7b3a04aa51e940d937e410534b059209ba6f1011d4d3056dd1f82c49e75105081e38e776ee5147a74f6802717dd2e3dad5f15b6b1c",
          "sha256": "bb16a84afcea3cfd9fc316772de09aef31037e909a348a6579ad0d0a7fce4450",
          "sha1": "9a7afb5c7ca0c41198a974694a6dcbdda823194b",
          "md5": "369647ff9a7780f135ee0fbad1b2c3fc"
        }
      ]
    }
  ]
}
