{
  "formatVersion": "1.1",
  "component": {
    "url": "../../abstract-red-black-priority-queue/1.0/abstract-red-black-priority-queue-1.0.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "abstract-red-black-priority-queue",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-tree",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-priority-queue.klib",
          "url": "abstract-red-black-priority-queue-tvosx64-1.0.klib",
          "size": 13423,
          "sha512": "19e7f0fe111adea5aead229c432b0c28aad253bfe16ecee76c346242b0776a587add6d09f796e3c9f22376359a1b8c7f88bc6055d50c9218c6084e1c30f05737",
          "sha256": "3f8e97ba35ee1a4f10c8a1e018a986d4951facf3e257b07750f2ed0f1533e14e",
          "sha1": "47aaee23cf732818a1008a8435dd1d1423d5d647",
          "md5": "1e7bf73d5e4eac9db0a194490fc5b261"
        }
      ]
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "abstract-red-black-priority-queue-tvosx64-1.0-sources.jar",
          "url": "abstract-red-black-priority-queue-tvosx64-1.0-sources.jar",
          "size": 2386,
          "sha512": "bf8eacd8269746ec6ae1a687f4921866ab7e60738d93bbd42343b091b02cea8b876cfc0def39265fa51964a892fd1d47ae11d07a9d10116c60baeb667fd948f4",
          "sha256": "f08bfd49ad8448dcd8b4e4d4eb30507be68b85370301794c305e1953f6b3755e",
          "sha1": "baed2e53dc52e001f9d48c5ee65759cbb09f5624",
          "md5": "e6cec4710f91cdc20677c3cda9c1d5b3"
        }
      ]
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-tree",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-priority-queue-tvosx64-1.0-metadata.jar",
          "url": "abstract-red-black-priority-queue-tvosx64-1.0-metadata.jar",
          "size": 261,
          "sha512": "bcd3facc0faff25b0759ae5566503de1bcc77b1510ee8e21463ade21e5a20ddd60c3c6f10b4d01520241c9700f92d704768a7788b82610dfe37fb38b3ee40e11",
          "sha256": "1a6a6b21d2c7476f05cc62209575372d237f30fc457338150545268003936eee",
          "sha1": "f45e29c6c1e9e90db71ff725f1be2710ae134dab",
          "md5": "a8f8a36b3a0c48f41faa3f78740227d5"
        }
      ]
    }
  ]
}
