{
  "formatVersion": "1.1",
  "component": {
    "url": "../../abstract-red-black-priority-queue/1.1/abstract-red-black-priority-queue-1.1.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "abstract-red-black-priority-queue",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-tree",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-priority-queue.klib",
          "url": "abstract-red-black-priority-queue-watchosarm32-1.1.klib",
          "size": 15006,
          "sha512": "e8a423e2b6b2ed85444c5ae69b5d556fd9e2d7e160ca2f1f95adf69506318b72cd0016d7ae260b270ab8bd4e64796c99c07a009b959a83b19178e5cea2233acb",
          "sha256": "6aa9e8e7306ab4b798045a7e636e13209ee509995241010a745657bb753d5e51",
          "sha1": "4bb49839d7facfc1bd7e676c3159c39d9bbedfa0",
          "md5": "3c6743949fd815dc1dc11722c8355fc6"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "abstract-red-black-priority-queue-watchosarm32-1.1-sources.jar",
          "url": "abstract-red-black-priority-queue-watchosarm32-1.1-sources.jar",
          "size": 2684,
          "sha512": "9295885cf78a625a118399347e8c739de0f5deaea4d82acea690cdb1752a6a70bc344f72f0f098f68831bc09c8941f428390621abfb6a9d108048eb95f74452b",
          "sha256": "31440029b58b89417ec68ea8046cc01e65c2b17e29ed7a645a62f0c57531ee91",
          "sha1": "751f0b2471becf15e9b13040b4a9e491128e8aaa",
          "md5": "4b55e277a7751ec73c43f5575edf8c14"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-tree",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-priority-queue-watchosarm32-1.1-metadata.jar",
          "url": "abstract-red-black-priority-queue-watchosarm32-1.1-metadata.jar",
          "size": 261,
          "sha512": "9b7e12b66c6330496d7f97768d323cfcf67e6aeb7509bdb697e19ae8ac0f9812bf3d1d381fa25aab628b6140a95da580131b776121b5c117cbb0e74dd93080dd",
          "sha256": "001013510c1e874429370c0d10612b9a115c20d761a4d2297f1506688dd1f74f",
          "sha1": "073ed2a80f1c0eaa89f4612f27a9c1bb6f271b28",
          "md5": "34fd29912461ac8575ba5ffbc52de8ff"
        }
      ]
    }
  ]
}
