{
  "formatVersion": "1.1",
  "component": {
    "url": "../../abstract-red-black-priority-queue/1.0/abstract-red-black-priority-queue-1.0.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "abstract-red-black-priority-queue",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-tree",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-priority-queue.klib",
          "url": "abstract-red-black-priority-queue-watchosarm32-1.0.klib",
          "size": 13465,
          "sha512": "56d0bd2acc7dd5414585973e95f63616f9482bb2354d84263f25914dc29cb8528b15494214603ad489d5bca44a4415611cd99ce9d1e17f3d251634a5f2a24c9c",
          "sha256": "e90fcbc86da598dc48fafa0771bd93e7ef8d424aa974f7740818beebe83976b0",
          "sha1": "06b5ff62781deccca46ba48db9aaf4beff434ea6",
          "md5": "3ef15a08668cb71c14b976763dd2172c"
        }
      ]
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "abstract-red-black-priority-queue-watchosarm32-1.0-sources.jar",
          "url": "abstract-red-black-priority-queue-watchosarm32-1.0-sources.jar",
          "size": 2386,
          "sha512": "bf8eacd8269746ec6ae1a687f4921866ab7e60738d93bbd42343b091b02cea8b876cfc0def39265fa51964a892fd1d47ae11d07a9d10116c60baeb667fd948f4",
          "sha256": "f08bfd49ad8448dcd8b4e4d4eb30507be68b85370301794c305e1953f6b3755e",
          "sha1": "baed2e53dc52e001f9d48c5ee65759cbb09f5624",
          "md5": "e6cec4710f91cdc20677c3cda9c1d5b3"
        }
      ]
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-tree",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-priority-queue-watchosarm32-1.0-metadata.jar",
          "url": "abstract-red-black-priority-queue-watchosarm32-1.0-metadata.jar",
          "size": 261,
          "sha512": "df24eef4baa29a202346f0cd17516c25eaeb4f3cc3aebd2ee310d7716b73bdc6841adecd980e087fba5eea6996095693bc7ce09070c07c0b7ab3eb4551ccba06",
          "sha256": "6edb2810a309a5e1cbca41472c4797c3bb107a0f0e3fc8df5ee0a70f9b96672f",
          "sha1": "ff0ca691f88ca822ffe35115305f147798ecd63a",
          "md5": "b650f54a2943047ee13ee738167c78ce"
        }
      ]
    }
  ]
}
