{
  "formatVersion": "1.1",
  "component": {
    "url": "../../abstract-red-black-priority-queue/1.0/abstract-red-black-priority-queue-1.0.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "abstract-red-black-priority-queue",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-tree",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-priority-queue.klib",
          "url": "abstract-red-black-priority-queue-iosx64-1.0.klib",
          "size": 13414,
          "sha512": "00241460eb101fda4a740cbb7ef3478dab98f0e6622c8495f4b41d2b48899dbd146bcbf63811ebe6a8e94a6b3821ba353c9b8be77860e15f74052a57a7691fa5",
          "sha256": "ee49f53f48a4a47aad9dec931a1c6414331a19856d7085745bd12c2c3fcf2c38",
          "sha1": "936c8405dfd5dbb419dfc276d91685715ebd50bd",
          "md5": "f446c1ec492af087090e88ca5352a6c5"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "abstract-red-black-priority-queue-iosx64-1.0-sources.jar",
          "url": "abstract-red-black-priority-queue-iosx64-1.0-sources.jar",
          "size": 2386,
          "sha512": "bf8eacd8269746ec6ae1a687f4921866ab7e60738d93bbd42343b091b02cea8b876cfc0def39265fa51964a892fd1d47ae11d07a9d10116c60baeb667fd948f4",
          "sha256": "f08bfd49ad8448dcd8b4e4d4eb30507be68b85370301794c305e1953f6b3755e",
          "sha1": "baed2e53dc52e001f9d48c5ee65759cbb09f5624",
          "md5": "e6cec4710f91cdc20677c3cda9c1d5b3"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-tree",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-priority-queue-iosx64-1.0-metadata.jar",
          "url": "abstract-red-black-priority-queue-iosx64-1.0-metadata.jar",
          "size": 261,
          "sha512": "47c62a9250f1675b4147bfccf3adce837dfb1dd2421efb0775e952c192ea99c9172aa28b028bc81a76ac5708021ffedb06aad375f40478e9e36d5e392ba80390",
          "sha256": "f8d5c0c4285b07a0bbc0859f712974f7129879201a67d9b198b5eae9fdbdc225",
          "sha1": "39105366a92876409b02bcdb1bd2f322fbae63f6",
          "md5": "d32f87162e8ffadc74dc774e9ba9d484"
        }
      ]
    }
  ]
}
