{
  "formatVersion": "1.1",
  "component": {
    "url": "../../abstract-red-black-priority-queue/1.1/abstract-red-black-priority-queue-1.1.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "abstract-red-black-priority-queue",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-tree",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-priority-queue.klib",
          "url": "abstract-red-black-priority-queue-iosx64-1.1.klib",
          "size": 14955,
          "sha512": "9c6bf0b540ae027c7616c8876a9d172398c627c190a9ef2ce460504ea89a17d802939c6f5077331df57c7e0abda4bca74edafc712c02051ff71afd56dcb8cc8a",
          "sha256": "f2043f854cfb58163abdf671483fb0624866ac1dc908b3f28b35efbfa0545bea",
          "sha1": "6c79b897002ca2c6afa4fa618cdf8c473904162b",
          "md5": "b85163f9836af3aab66bfe46f5e9c64f"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "abstract-red-black-priority-queue-iosx64-1.1-sources.jar",
          "url": "abstract-red-black-priority-queue-iosx64-1.1-sources.jar",
          "size": 2684,
          "sha512": "9295885cf78a625a118399347e8c739de0f5deaea4d82acea690cdb1752a6a70bc344f72f0f098f68831bc09c8941f428390621abfb6a9d108048eb95f74452b",
          "sha256": "31440029b58b89417ec68ea8046cc01e65c2b17e29ed7a645a62f0c57531ee91",
          "sha1": "751f0b2471becf15e9b13040b4a9e491128e8aaa",
          "md5": "4b55e277a7751ec73c43f5575edf8c14"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-tree",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-priority-queue-iosx64-1.1-metadata.jar",
          "url": "abstract-red-black-priority-queue-iosx64-1.1-metadata.jar",
          "size": 261,
          "sha512": "36fca4f2f1ddbfd54cf4ae4ee847a1f008934a1b3b7a6065147c7b3221fdab11159d641e3051eca018096b51947e3c20eecffa3be281c469b6e1cbfa293f29d8",
          "sha256": "2a0491548bdc2021ef38e8f97c88bb4ac1069b84ce768bc7d1ffd04186b03535",
          "sha1": "148766ba3a6cee0f1acf27b1944e36a537c6af96",
          "md5": "6633ff1fb48b65cd988a82d435450b94"
        }
      ]
    }
  ]
}
