{
  "formatVersion": "1.1",
  "component": {
    "url": "../../abstract-red-black-priority-queue/1.1/abstract-red-black-priority-queue-1.1.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "abstract-red-black-priority-queue",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-tree",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-priority-queue.klib",
          "url": "abstract-red-black-priority-queue-tvosarm64-1.1.klib",
          "size": 14980,
          "sha512": "aa80487ba0548df8e10c80406cbe9932585154fbda1274ddaeeb3fa5b09b26173de2acc2bb0222bb4115033ea035846815576b71aa63764b4205c6003e4299a1",
          "sha256": "74b9f89dc133626f5cc6865fb883491cd4698df772294af32fa47e939cadfc29",
          "sha1": "29e3482354cdedc2b3bee7908593eb9581023569",
          "md5": "212c0e899a5b44ef0f68fbbca351c0e7"
        }
      ]
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "abstract-red-black-priority-queue-tvosarm64-1.1-sources.jar",
          "url": "abstract-red-black-priority-queue-tvosarm64-1.1-sources.jar",
          "size": 2684,
          "sha512": "9295885cf78a625a118399347e8c739de0f5deaea4d82acea690cdb1752a6a70bc344f72f0f098f68831bc09c8941f428390621abfb6a9d108048eb95f74452b",
          "sha256": "31440029b58b89417ec68ea8046cc01e65c2b17e29ed7a645a62f0c57531ee91",
          "sha1": "751f0b2471becf15e9b13040b4a9e491128e8aaa",
          "md5": "4b55e277a7751ec73c43f5575edf8c14"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-tree",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-priority-queue-tvosarm64-1.1-metadata.jar",
          "url": "abstract-red-black-priority-queue-tvosarm64-1.1-metadata.jar",
          "size": 261,
          "sha512": "a89bf1f42fc6c6a22bc4946ddde55e31b2141e636efd7529eea0af6dccbf079f365506e0ffa773fe3cd27932c56bc4d6a7a82992bafbb0c01560baa2510e06b1",
          "sha256": "7c9494d8cd555b01bb90febd7093ca2f994cbab876afc34b7d1190d6d807c75b",
          "sha1": "ad98cd3af6d54ac13b4c73b1b2b2e70d624bfa14",
          "md5": "edcd28019210db1760025b7484261439"
        }
      ]
    }
  ]
}
