{
  "formatVersion": "1.1",
  "component": {
    "url": "../../abstract-red-black-priority-queue/1.0/abstract-red-black-priority-queue-1.0.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "abstract-red-black-priority-queue",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-tree",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-priority-queue.klib",
          "url": "abstract-red-black-priority-queue-tvosarm64-1.0.klib",
          "size": 13439,
          "sha512": "9e27c0cd41ff2326e12e5961bd62737e20a7ee403a29f73e814c2cbd922bf5bf756a4a47a60c5de31a67f587e0b597d29a9fe2c3301940b6af6a4be32d8151d2",
          "sha256": "e2815e3a551ee329ee91e1213eea5ff9abf0ef00b8ce0d05203dcddaa4dae923",
          "sha1": "eacc62fd18a0582188622d9a3ba94f3ac0b86b60",
          "md5": "dac3e99d701165eb9a6bde3069c6ff64"
        }
      ]
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "abstract-red-black-priority-queue-tvosarm64-1.0-sources.jar",
          "url": "abstract-red-black-priority-queue-tvosarm64-1.0-sources.jar",
          "size": 2386,
          "sha512": "bf8eacd8269746ec6ae1a687f4921866ab7e60738d93bbd42343b091b02cea8b876cfc0def39265fa51964a892fd1d47ae11d07a9d10116c60baeb667fd948f4",
          "sha256": "f08bfd49ad8448dcd8b4e4d4eb30507be68b85370301794c305e1953f6b3755e",
          "sha1": "baed2e53dc52e001f9d48c5ee65759cbb09f5624",
          "md5": "e6cec4710f91cdc20677c3cda9c1d5b3"
        }
      ]
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-tree",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-priority-queue-tvosarm64-1.0-metadata.jar",
          "url": "abstract-red-black-priority-queue-tvosarm64-1.0-metadata.jar",
          "size": 261,
          "sha512": "7be7f6933af1ed54bb6a36b0c3ba94b01c306fab5b073e881ccdabb0cf0609d0a4e74671a78a38df93b4f4de9bfb425c3c363184038a325faea4bad341bd49f1",
          "sha256": "eccdeed021d595540c078244d769270dee11b7535b789ca95dc696ee88bbdb14",
          "sha1": "da45d7de91eb4c4409cdd327363ede0582635997",
          "md5": "ad44715510eadd2ddc8bfd9af593b5d0"
        }
      ]
    }
  ]
}
