{
  "formatVersion": "1.1",
  "component": {
    "url": "../../abstract-red-black-priority-queue/1.1/abstract-red-black-priority-queue-1.1.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "abstract-red-black-priority-queue",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-tree",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-priority-queue.klib",
          "url": "abstract-red-black-priority-queue-iosarm64-1.1.klib",
          "size": 14971,
          "sha512": "3c67aca60a72fa0d9982fe2e1ec9b647233d863f130f5ce22062c5395227f90f87cbe9fb8c92c70b2c6a5bba7a503630cbf52116eb1d0be4d029af79f4d0ce7f",
          "sha256": "b3fcdb1d817580d4c4fcf9082520ec2dfc56a78cd879f44b8bafc1cee4655d9f",
          "sha1": "4c4dceb1f2ef0defc8e3251359b626ccc3a2a76d",
          "md5": "ba718bb4714c2b89b6588c1b98d0c8cd"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "abstract-red-black-priority-queue-iosarm64-1.1-sources.jar",
          "url": "abstract-red-black-priority-queue-iosarm64-1.1-sources.jar",
          "size": 2684,
          "sha512": "9295885cf78a625a118399347e8c739de0f5deaea4d82acea690cdb1752a6a70bc344f72f0f098f68831bc09c8941f428390621abfb6a9d108048eb95f74452b",
          "sha256": "31440029b58b89417ec68ea8046cc01e65c2b17e29ed7a645a62f0c57531ee91",
          "sha1": "751f0b2471becf15e9b13040b4a9e491128e8aaa",
          "md5": "4b55e277a7751ec73c43f5575edf8c14"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-tree",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-priority-queue-iosarm64-1.1-metadata.jar",
          "url": "abstract-red-black-priority-queue-iosarm64-1.1-metadata.jar",
          "size": 261,
          "sha512": "36fca4f2f1ddbfd54cf4ae4ee847a1f008934a1b3b7a6065147c7b3221fdab11159d641e3051eca018096b51947e3c20eecffa3be281c469b6e1cbfa293f29d8",
          "sha256": "2a0491548bdc2021ef38e8f97c88bb4ac1069b84ce768bc7d1ffd04186b03535",
          "sha1": "148766ba3a6cee0f1acf27b1944e36a537c6af96",
          "md5": "6633ff1fb48b65cd988a82d435450b94"
        }
      ]
    }
  ]
}
