{
  "formatVersion": "1.1",
  "component": {
    "url": "../../abstract-red-black-priority-queue/1.0/abstract-red-black-priority-queue-1.0.module",
    "group": "ru.landgrafhomyak.collections",
    "module": "abstract-red-black-priority-queue",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-tree",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-priority-queue.klib",
          "url": "abstract-red-black-priority-queue-iossimulatorarm64-1.0.klib",
          "size": 13517,
          "sha512": "94ac8e36be84bc86859cc07326ac07327c0eb260633c2ce0587dde25fd30c652f5a0cd2d1bf6ce1d64f5acaf3e3156741ff1f372ee01ceeed5fce8135830244f",
          "sha256": "5a8e4f62bc0264a39259367237df7873d53468697c8627ca8edb0d39ecad118a",
          "sha1": "1f35b9bb671af4fceb173d7eac92f0a5f52daa59",
          "md5": "065ef22c67c5b784dd71339de1aa664e"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "abstract-red-black-priority-queue-iossimulatorarm64-1.0-sources.jar",
          "url": "abstract-red-black-priority-queue-iossimulatorarm64-1.0-sources.jar",
          "size": 2386,
          "sha512": "bf8eacd8269746ec6ae1a687f4921866ab7e60738d93bbd42343b091b02cea8b876cfc0def39265fa51964a892fd1d47ae11d07a9d10116c60baeb667fd948f4",
          "sha256": "f08bfd49ad8448dcd8b4e4d4eb30507be68b85370301794c305e1953f6b3755e",
          "sha1": "baed2e53dc52e001f9d48c5ee65759cbb09f5624",
          "md5": "e6cec4710f91cdc20677c3cda9c1d5b3"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "ru.landgrafhomyak.collections",
          "module": "abstract-red-black-tree",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "abstract-red-black-priority-queue-iossimulatorarm64-1.0-metadata.jar",
          "url": "abstract-red-black-priority-queue-iossimulatorarm64-1.0-metadata.jar",
          "size": 261,
          "sha512": "45187b814c0bddca041b4e9ec5e824497076bffaf4b09a05bcfd60d863aaa397cf4d4b6a86f213d8753be9a831ab095a8bcfaddbde519fb0ca8298a768fa4b75",
          "sha256": "597b522ca5db9c1ed632db8d7c2974eda3a8fadd4dbf1b4d3f665942e98643ea",
          "sha1": "b4951f5900b1ef29ef911abefc859cf5c61a49f1",
          "md5": "0ecf98eb2b39907a35a913c2adf08e4c"
        }
      ]
    }
  ]
}
